# Generated by Django 2.0.9 on 2019-10-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0003_auto_20191003_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibiotic',
            name='alias',
            field=models.CharField(default='_', max_length=64, verbose_name='antibioticType'),
        ),
    ]
