# Generated by Django 2.0.9 on 2019-12-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0004_antibiotic_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='facilityStr',
            field=models.CharField(default='_', max_length=128, verbose_name='facilityStr'),
        ),
    ]
