# Generated by Django 2.0.9 on 2018-11-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathogen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='pathogen name')),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='pathogen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='newick.Pathogen'),
            preserve_default=False,
        ),
    ]
