# Generated by Django 2.0.9 on 2018-11-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0002_auto_20181105_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathogen',
            name='name',
        ),
    ]
