# Generated by Django 2.0.9 on 2018-11-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0003_remove_pathogen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathogen',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='pathogen name'),
            preserve_default=False,
        ),
    ]
