# Generated by Django 2.0.9 on 2018-11-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0004_pathogen_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathogen',
            old_name='id',
            new_name='pathogenId',
        ),
        migrations.RenameField(
            model_name='pathogen',
            old_name='name',
            new_name='pathogenName',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='dataFile',
            new_name='sequenceDataFile',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='date',
            new_name='sequenceDate',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='group',
            new_name='sequenceGroup',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='id',
            new_name='sequenceId',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='location',
            new_name='sequenceLocation',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='name',
            new_name='sequenceName',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='pathogen',
            new_name='sequencePathogen',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='user',
            new_name='sequenceUser',
        ),
    ]
