# Generated by Django 2.0.9 on 2018-11-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0005_auto_20181105_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pathogen',
            old_name='pathogenId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pathogen',
            old_name='pathogenName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequenceDataFile',
            new_name='dataFile',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequenceDate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequenceGroup',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequenceId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequenceLocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequenceName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequencePathogen',
            new_name='pathogen',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequenceUser',
            new_name='user',
        ),
    ]
