# Generated by Django 2.0.9 on 2018-11-05 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newick', '0006_auto_20181105_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='sample name')),
                ('date', models.DateField(verbose_name='date published')),
                ('location', models.CharField(max_length=100, verbose_name='address')),
                ('dataFile', models.CharField(max_length=250, verbose_name='sequence file')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('pathogen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newick.Pathogen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='pathogen',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='sequences',
        ),
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.AddField(
            model_name='tree',
            name='samples',
            field=models.ManyToManyField(to='newick.Sample'),
        ),
    ]
