# Generated by Django 2.0.9 on 2019-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0007_auto_20181105_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='CountyName')),
            ],
        ),
        migrations.CreateModel(
            name='MPC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='MajorPopulationCenter')),
            ],
        ),
        migrations.CreateModel(
            name='PCA',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='PcaNumber')),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='group',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='pathogen',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='samples',
        ),
        migrations.DeleteModel(
            name='Pathogen',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
