# Generated by Django 2.0.9 on 2019-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0008_auto_20190625_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mpc',
            name='name',
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='CountyName'),
        ),
        migrations.AlterField(
            model_name='mpc',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='MajorPopulationCenter'),
        ),
    ]
