# Generated by Django 2.0.9 on 2019-06-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0010_county_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='PcaName'),
        ),
        migrations.AddField(
            model_name='pca',
            name='polygons',
            field=models.TextField(default='', max_length=50000, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='county',
            name='polygon',
            field=models.TextField(default='', max_length=10000, verbose_name='Polygon'),
        ),
    ]
