# Generated by Django 2.0.9 on 2019-06-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0011_auto_20190625_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='polygon',
            field=models.TextField(default='[]', max_length=10000, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='id',
            field=models.PositiveSmallIntegerField(verbose_name='PcaNumber'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='PcaName'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='polygons',
            field=models.TextField(default='[]', max_length=50000, verbose_name='Polygon'),
        ),
    ]
