# Generated by Django 2.0.9 on 2019-06-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0015_auto_20190625_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pca',
            name='polygon',
        ),
        migrations.AddField(
            model_name='pca',
            name='name',
            field=models.CharField(default='-', max_length=50, verbose_name='PcaName'),
        ),
        migrations.AddField(
            model_name='pca',
            name='polygons',
            field=models.TextField(default='[]', max_length=50000, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='PcaNumber'),
        ),
    ]
