# Generated by Django 2.0.9 on 2019-06-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0017_auto_20190625_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pca',
            old_name='polygon',
            new_name='polygons',
        ),
    ]
