# Generated by Django 2.0.9 on 2019-06-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0019_auto_20190625_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pca',
            name='name',
        ),
        migrations.AlterField(
            model_name='pca',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='PcaName'),
        ),
    ]
