# Generated by Django 2.0.9 on 2019-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0020_auto_20190625_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pca',
            name='polygon',
            field=models.CharField(default='[]', max_length=50000, verbose_name='Polygon'),
        ),
    ]
