# Generated by Django 2.0.9 on 2019-06-26 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0022_auto_20190625_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='amrId')),
                ('date', models.DateField(verbose_name='amrDate')),
                ('tested', models.PositiveSmallIntegerField(default=0, verbose_name='numberTested')),
                ('suseptable', models.PositiveSmallIntegerField(default=0, verbose_name='percentSuseptable')),
            ],
        ),
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='bacteriaId')),
                ('name', models.CharField(default='_', max_length=50, verbose_name='bacteriaName')),
                ('type', models.CharField(default='_', max_length=50, verbose_name='bacteriaType')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='drugId')),
                ('name', models.CharField(default='_', max_length=50, verbose_name='drugName')),
                ('type', models.CharField(default='_', max_length=50, verbose_name='drugType')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='facilityId')),
                ('name', models.CharField(default='_', max_length=50, verbose_name='facilityName')),
                ('type', models.CharField(default='_', max_length=50, verbose_name='facilityType')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='regionName')),
            ],
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='countyName'),
        ),
        migrations.AlterField(
            model_name='county',
            name='polygon',
            field=models.TextField(default='[]', max_length=10000, verbose_name='polygon'),
        ),
        migrations.AlterField(
            model_name='mpc',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='majorPopulationCenter'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='pcaName'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='polygon',
            field=models.TextField(default='[]', max_length=50000, verbose_name='polygon'),
        ),
        migrations.AddField(
            model_name='amr',
            name='bacteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newick.Bacteria'),
        ),
        migrations.AddField(
            model_name='amr',
            name='drup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newick.Drug'),
        ),
        migrations.AddField(
            model_name='amr',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newick.Facility'),
        ),
    ]
