# Generated by Django 2.0.9 on 2019-06-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0023_auto_20190626_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amr',
            old_name='drup',
            new_name='drug',
        ),
    ]
