# Generated by Django 2.0.9 on 2019-06-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0024_auto_20190626_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoAMR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='amrId')),
                ('date', models.DateField(verbose_name='amrDate')),
                ('tested', models.PositiveSmallIntegerField(default=0, verbose_name='numberTested')),
                ('suseptable', models.PositiveSmallIntegerField(default=0, verbose_name='percentSuseptable')),
                ('bacteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newick.Bacteria')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newick.Drug')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newick.Facility')),
            ],
        ),
    ]
