# Generated by Django 2.0.9 on 2019-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0025_demoamr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacteria',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='bacteriaName'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='drugName'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='siteId'),
        ),
    ]
