# Generated by Django 2.0.9 on 2019-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0026_auto_20190626_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amr',
            name='date',
        ),
        migrations.AddField(
            model_name='amr',
            name='year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='amrYear'),
        ),
    ]
