# Generated by Django 2.0.9 on 2019-06-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0029_auto_20190626_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='amr',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.Facility'),
        ),
        migrations.AddField(
            model_name='demoamr',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.Facility'),
        ),
        migrations.AlterField(
            model_name='amr',
            name='bacteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.Bacteria'),
        ),
        migrations.AlterField(
            model_name='amr',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.Drug'),
        ),
        migrations.AlterField(
            model_name='demoamr',
            name='bacteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.Bacteria'),
        ),
        migrations.AlterField(
            model_name='demoamr',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.Drug'),
        ),
    ]
