# Generated by Django 2.0.9 on 2019-06-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0030_auto_20190626_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='pca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.PCA'),
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.Region'),
        ),
        migrations.AddField(
            model_name='facility',
            name='mpc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.MPC'),
        ),
        migrations.AddField(
            model_name='pca',
            name='mpc1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpc1', to='newick.MPC'),
        ),
        migrations.AddField(
            model_name='pca',
            name='mpc2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpc2', to='newick.MPC'),
        ),
        migrations.AddField(
            model_name='pca',
            name='mpc3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpc3', to='newick.MPC'),
        ),
    ]
