# Generated by Django 2.0.9 on 2019-06-26 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0031_auto_20190626_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyPCA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='bridgeId')),
            ],
        ),
        migrations.RemoveField(
            model_name='county',
            name='pca',
        ),
        migrations.AddField(
            model_name='countypca',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.County'),
        ),
        migrations.AddField(
            model_name='countypca',
            name='pca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newick.PCA'),
        ),
    ]
