# Generated by Django 2.0.9 on 2019-06-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0033_auto_20190626_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='pca',
            name='polygon',
        ),
    ]
