# Generated by Django 2.0.9 on 2019-06-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0035_auto_20190626_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amr',
            name='year',
            field=models.DateField(verbose_name='amrYear'),
        ),
        migrations.AlterField(
            model_name='demoamr',
            name='year',
            field=models.DateField(verbose_name='amrYear'),
        ),
    ]
