# Generated by Django 2.0.9 on 2019-06-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0036_auto_20190626_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amr',
            name='year',
        ),
        migrations.RemoveField(
            model_name='demoamr',
            name='year',
        ),
        migrations.AddField(
            model_name='amr',
            name='date',
            field=models.DateField(default='2000-1-1', verbose_name='amrDate'),
        ),
        migrations.AddField(
            model_name='demoamr',
            name='date',
            field=models.DateField(default='2000-1-1', verbose_name='amrDate'),
        ),
    ]
