# Generated by Django 2.0.9 on 2019-06-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0037_auto_20190626_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bacteria',
            options={'ordering': ('type', 'id')},
        ),
    ]
