# Generated by Django 2.0.9 on 2019-06-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0039_auto_20190627_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amr',
            options={'ordering': ['date', 'facility', 'bacteria', 'drug']},
        ),
        migrations.AlterModelOptions(
            name='bacteria',
            options={'ordering': ['type', 'id']},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='countypca',
            options={'ordering': ['county', 'pca']},
        ),
        migrations.AlterModelOptions(
            name='demoamr',
            options={'ordering': ['date', 'facility', 'bacteria', 'drug']},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['type', 'id']},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['mpc', 'type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='mpc',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pca',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='facilityId'),
        ),
    ]
