# Generated by Django 2.0.9 on 2019-06-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0041_auto_20190627_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name']},
        ),
    ]
