# Generated by Django 2.0.9 on 2019-06-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0042_auto_20190627_0031'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('id', 'name')},
        ),
    ]
