# Generated by Django 2.0.9 on 2019-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0043_auto_20190627_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('mpc', 'id')},
        ),
    ]
