# Generated by Django 2.0.9 on 2019-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0045_auto_20190708_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='pca',
            name='azmua',
            field=models.CharField(default='_', max_length=50, verbose_name='AzMUA'),
        ),
        migrations.AddField(
            model_name='pca',
            name='fedmuap',
            field=models.CharField(default='_', max_length=250, verbose_name='FedMUAP'),
        ),
        migrations.AddField(
            model_name='pca',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='pcaNumber'),
        ),
        migrations.AddField(
            model_name='pca',
            name='pchpsa',
            field=models.CharField(default='_', max_length=250, verbose_name='PCHPSA'),
        ),
        migrations.AddField(
            model_name='pca',
            name='rural',
            field=models.CharField(default='_', max_length=10, verbose_name='ruralCode'),
        ),
        migrations.AddField(
            model_name='pca',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='pcaScore'),
        ),
        migrations.AddField(
            model_name='pca',
            name='tax',
            field=models.CharField(default='_', max_length=2, verbose_name='taxDistrict'),
        ),
        migrations.AddField(
            model_name='pca',
            name='travel2',
            field=models.CharField(default='_', max_length=50, verbose_name='travel2'),
        ),
        migrations.AddField(
            model_name='pca',
            name='travel3',
            field=models.CharField(default='_', max_length=50, verbose_name='travel3'),
        ),
    ]
