# Generated by Django 2.0.9 on 2019-07-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0046_auto_20190719_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mpc',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='pca',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='region',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='county',
            name='lat',
            field=models.CharField(default='_', max_length=16, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='county',
            name='lon',
            field=models.CharField(default='_', max_length=16, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='facility',
            name='address',
            field=models.CharField(default='_', max_length=64, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='facility',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='capacity'),
        ),
        migrations.AddField(
            model_name='facility',
            name='certification',
            field=models.CharField(default='_', max_length=1, verbose_name='certification'),
        ),
        migrations.AddField(
            model_name='facility',
            name='fax',
            field=models.CharField(default='_', max_length=16, verbose_name='faxNumber'),
        ),
        migrations.AddField(
            model_name='facility',
            name='lat',
            field=models.CharField(default='_', max_length=16, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='facility',
            name='lon',
            field=models.CharField(default='_', max_length=16, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='facility',
            name='phone',
            field=models.CharField(default='_', max_length=16, verbose_name='phoneNumber'),
        ),
        migrations.AddField(
            model_name='facility',
            name='zip',
            field=models.CharField(default='_', max_length=16, verbose_name='zipCode'),
        ),
        migrations.AddField(
            model_name='mpc',
            name='lat',
            field=models.CharField(default='_', max_length=16, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='mpc',
            name='lon',
            field=models.CharField(default='_', max_length=16, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='pca',
            name='lat',
            field=models.CharField(default='_', max_length=16, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='pca',
            name='lon',
            field=models.CharField(default='_', max_length=16, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='region',
            name='lat',
            field=models.CharField(default='_', max_length=16, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='region',
            name='lon',
            field=models.CharField(default='_', max_length=16, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='bacteriaName'),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='type',
            field=models.CharField(default='_', max_length=64, verbose_name='bacteriaType'),
        ),
        migrations.AlterField(
            model_name='county',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='countyName'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='drugName'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(default='_', max_length=64, verbose_name='drugType'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='facilityName'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='mpc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpc', to='newick.MPC'),
        ),
        migrations.AlterField(
            model_name='mpc',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='majorPopulationCenter'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='azmua',
            field=models.CharField(default='_', max_length=64, verbose_name='AzMUA'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='fedmuap',
            field=models.CharField(default='_', max_length=256, verbose_name='FedMUAP'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='pcaName'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='pchpsa',
            field=models.CharField(default='_', max_length=256, verbose_name='PCHPSA'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='rural',
            field=models.CharField(default='_', max_length=16, verbose_name='ruralCode'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='travel2',
            field=models.CharField(default='_', max_length=64, verbose_name='travel2'),
        ),
        migrations.AlterField(
            model_name='pca',
            name='travel3',
            field=models.CharField(default='_', max_length=64, verbose_name='travel3'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='regionName'),
        ),
    ]
