# Generated by Django 2.0.9 on 2019-07-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0048_auto_20190722_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitytype',
            options={},
        ),
        migrations.RenameField(
            model_name='facilitytype',
            old_name='thing',
            new_name='type1',
        ),
        migrations.RenameField(
            model_name='facilitytype',
            old_name='sub',
            new_name='type2',
        ),
        migrations.AlterUniqueTogether(
            name='facilitytype',
            unique_together={('type1', 'type2')},
        ),
    ]
