# Generated by Django 2.0.9 on 2019-07-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0049_auto_20190722_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='facilitytype',
            unique_together=set(),
        ),
    ]
