# Generated by Django 2.0.9 on 2019-07-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0050_auto_20190722_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitytype',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='facilitytype',
            unique_together={('type1', 'type2')},
        ),
        migrations.AddIndex(
            model_name='facilitytype',
            index=models.Index(fields=['type1', 'type2'], name='newick_faci_type1_c9c78f_idx'),
        ),
    ]
