# Generated by Django 2.0.9 on 2019-07-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0051_auto_20190722_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitytype',
            name='type1',
            field=models.CharField(db_index=True, max_length=64, verbose_name='facilityType'),
        ),
    ]
