# Generated by Django 2.0.9 on 2019-07-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0052_auto_20190722_2330'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facilitytype',
            name='newick_faci_type1_c9c78f_idx',
        ),
        migrations.AddIndex(
            model_name='facilitytype',
            index=models.Index(fields=['type1', 'type2'], name='stuff'),
        ),
    ]
