# Generated by Django 2.0.9 on 2019-07-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0053_auto_20190722_2331'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='facilitytype',
            name='stuff',
        ),
    ]
