# Generated by Django 2.0.9 on 2019-07-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newick', '0054_auto_20190722_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amr',
            name='suseptable',
        ),
        migrations.RemoveField(
            model_name='demoamr',
            name='suseptable',
        ),
        migrations.AddField(
            model_name='amr',
            name='susceptible',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='percentSusceptible'),
        ),
        migrations.AddField(
            model_name='demoamr',
            name='susceptible',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='percentSusceptible'),
        ),
    ]
